r"""Chat at the console with a model trained by ``PESFT``.

Loads a saved adapter directory (or merged model, or Hub id) with Unsloth,
applies a chat template and keeps the whole conversation as context for
each reply. Use the same ``--chat_template`` and ``--system_prompt`` the
model was trained with; the defaults (``chatml``, pirate prompt) match
``examples/instruct/instruct.py``.

Usage:
    uv run python -m examples.chat --model_name_or_path ./model-it \
        --system_prompt "Always answer like a pirate."

``exit``, ``quit``, Ctrl+C or Ctrl+D stops. Needs a GPU (Unsloth). See
``examples/instruct/README.md``.
"""

from __future__ import annotations

import argparse
import os
import warnings
from typing import Final, Protocol, runtime_checkable


# protobuf's compiled backend refuses descriptors generated by an older
# protoc, such as transformers' sentencepiece model protos; the pure-Python
# backend accepts them. Must be set before anything imports protobuf.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

# unsloth must be imported before transformers so its patches apply.
import unsloth
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template


print(unsloth.__version__)

# Unsloth wraps torch.__getattr__, so torch's own filter for these
# deprecation warnings (keyed on module "torch") does not match.
warnings.filterwarnings(
    "ignore",
    message=".*is deprecated, please use.*",
    category=UserWarning,
    module="unsloth.import_fixes",
)

DEFAULT_SYSTEM_PROMPT: Final[str] = (
    "You are a pirate, always respond in pirate speech."
)
DEFAULT_MAX_SEQ_LENGTH: Final[int] = 4096


@runtime_checkable
class SupportsGenerationConfig(Protocol):
    """Protocol for models exposing a generation_config attribute.

    Attributes:
        generation_config: The model's generation configuration object.
    """

    generation_config: object


@runtime_checkable
class SupportsThinkingToggle(Protocol):
    """Protocol for configs exposing an enable_thinking flag.

    Attributes:
        enable_thinking: Whether the chat template emits thinking tokens.
    """

    enable_thinking: bool


def parse_args() -> argparse.Namespace:
    """Parse command line arguments.

    Returns:
        Namespace with the model path, generation and loading options.
    """
    parser = argparse.ArgumentParser(
        description="Interactive chat with a PESFT instruction-tuned model"
    )

    parser.add_argument(
        "--model_name_or_path",
        type=str,
        required=True,
        help=(
            "Hub id or local directory of the trained adapters or merged "
            "model (required; instruct.py writes ./models/speftr-instruction "
            "by default)"
        ),
    )

    parser.add_argument(
        "--max_new_tokens",
        type=int,
        default=512,
        help="Maximum tokens to generate (default: 512).",
    )

    parser.add_argument(
        "--temperature",
        type=float,
        default=0.7,
        help="Generation temperature (default: 0.7).",
    )

    parser.add_argument(
        "--top_p",
        type=float,
        default=0.9,
        help="Nucleus sampling top_p (default: 0.9).",
    )

    parser.add_argument(
        "--chat_template",
        type=str,
        default="chatml",
        help="Chat template to use (default: chatml).",
    )

    parser.add_argument(
        "--load_in_4bit",
        action="store_true",
        help="Enable 4-bit loading (default: disabled).",
    )

    parser.add_argument(
        "--max_seq_length",
        type=int,
        default=DEFAULT_MAX_SEQ_LENGTH,
        help=(
            "Maximum sequence length to allocate for the model "
            f"(default: {DEFAULT_MAX_SEQ_LENGTH})."
        ),
    )

    parser.add_argument(
        "--system_prompt",
        type=str,
        default=DEFAULT_SYSTEM_PROMPT,
        help=(
            "System prompt to prepend to every conversation "
            "(default: pirate instructions)."
        ),
    )

    return parser.parse_args()


def _disable_thinking_mode(model: object) -> None:
    """Disable thinking tokens if the model supports them.

    Models without a ``generation_config``, or whose config lacks an
    ``enable_thinking`` flag, are left untouched.

    Args:
        model: Loaded model whose generation config is updated in place.

    Returns:
        None. The model's generation config is mutated in place.
    """
    if not isinstance(model, SupportsGenerationConfig):
        return
    generation_config = model.generation_config
    if isinstance(generation_config, SupportsThinkingToggle):
        generation_config.enable_thinking = False


def _stop_token_ids(model: object, tokenizer: object) -> list[int]:
    """Token ids that end a reply: the model's and the tokenizer's EOS.

    Qwen 3.5 checkpoints declare only ``<|endoftext|>`` as end of
    sequence while their chat turns end with the tokenizer's EOS,
    ``<|im_end|>``; a fine-tuned adapter emits only the latter.

    Args:
        model: Loaded model with a ``generation_config``.
        tokenizer: Its tokenizer.

    Returns:
        Sorted, de-duplicated ids.
    """
    configured = getattr(
        getattr(model, "generation_config", None), "eos_token_id", None
    )
    ids = set(configured if isinstance(configured, list) else [configured])
    ids.add(getattr(tokenizer, "eos_token_id", None))
    return sorted(i for i in ids if isinstance(i, int))


def main() -> None:
    """Load the model and run the interactive chat loop until exit.

    Returns:
        None. Exits on ``exit``/``quit``, EOF or keyboard interrupt.
    """
    args = parse_args()
    system_prompt = args.system_prompt.strip() or DEFAULT_SYSTEM_PROMPT

    print(f"Loading model from {args.model_name_or_path}...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model_name_or_path,
        max_seq_length=args.max_seq_length,
        dtype=None,
        load_in_4bit=args.load_in_4bit,
    )

    tokenizer = get_chat_template(
        tokenizer,
        chat_template=args.chat_template,
    )

    if hasattr(tokenizer, "default_system_prompt"):
        tokenizer.default_system_prompt = system_prompt

    FastLanguageModel.for_inference(model)
    # Generation is bounded by max_new_tokens; a max_length saved with the
    # checkpoint would otherwise conflict with it.
    model.generation_config.max_length = None
    _disable_thinking_mode(model)

    print("\n" + "=" * 60)
    print("Interactive Chat")
    print("=" * 60)
    print(
        "Type your messages and press Enter. "
        "Type 'exit' or 'quit' to stop, or press Ctrl+C/Ctrl+D."
    )
    print("=" * 60 + "\n")

    conversation_history: list[dict[str, str]] = [
        {"role": "system", "content": system_prompt},
    ]

    try:
        while True:
            try:
                user_input = input("\nYou: ")
            except EOFError:
                print("\n\nReceived EOF. Exiting.")
                break

            user_input = user_input.strip()

            if not user_input:
                print("Empty message; type a message or 'exit'.")
                continue

            if user_input.lower() in {"exit", "quit"}:
                print("Exiting chat.")
                break

            conversation_history.append(
                {"role": "user", "content": user_input}
            )

            prompt_text = tokenizer.apply_chat_template(
                conversation_history,
                tokenize=False,
                add_generation_prompt=True,
            )
            encoded = tokenizer(
                prompt_text,
                return_tensors="pt",
                padding=False,
            )
            input_ids = encoded["input_ids"].to(model.device)
            attention_mask = encoded.get("attention_mask")
            if attention_mask is not None:
                attention_mask = attention_mask.to(model.device)

            outputs = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_new_tokens=args.max_new_tokens,
                temperature=args.temperature,
                top_p=args.top_p,
                do_sample=args.temperature > 0,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=_stop_token_ids(model, tokenizer),
            )

            generated_tokens = outputs[0][input_ids.shape[1] :]
            response = tokenizer.decode(
                generated_tokens,
                skip_special_tokens=True,
            ).strip()

            print(f"\033[1;34mAssistant:\033[0m {response}")

            conversation_history.append(
                {"role": "assistant", "content": response}
            )

    except KeyboardInterrupt:
        print("\n\nInterrupted. Exiting.")


if __name__ == "__main__":
    main()
