r"""Instruction-tune a small chat model with ``PESFT`` (Dolly pirate).

Demonstrates chat SFT on instruction/context/response rows: each row
becomes a system + user + assistant conversation rendered with a chat
template, and only the assistant turn is trained. Shows

- ``_build_config``: ``PESFTConfig`` with ``chat_template``,
  ``train_on_responses`` and the ChatML ``instruction_part`` /
  ``response_part`` markers;
- ``_build_conversations_from_columns`` / ``_build_format_batch``: the
  batched formatting function ``PESFT.train`` expects (a ``messages``
  column of role/content lists is used as is, if present);
- ``main``: ``PESFT(config)`` -> ``load_model()`` -> ``train()`` ->
  ``save_model()``.

The dataset (``TeeZee/dolly-15k-pirate-speech``, 15,011 rows) has pirate
speech only in the responses; 5% is held out for evaluation.

Usage:
    uv run python -m examples.instruct.instruct \
        --output_dir ./model-it --load_in_4bit --num_epochs 1
    uv run python -m examples.instruct.instruct --help

Talk to the result with ``python -m examples.chat``. Data, outputs and how
to adapt it: ``examples/instruct/README.md``.
"""

from __future__ import annotations

import argparse
import os
from typing import (
    TYPE_CHECKING,
    Final,
    Protocol,
    cast,
    runtime_checkable,
)


# protobuf's compiled backend refuses descriptors generated by an older
# protoc, such as transformers' sentencepiece model protos; the pure-Python
# backend accepts them. Must be set before anything imports protobuf.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

# unsloth must be imported before datasets/transformers/trl so its patches
# apply to everything imported after it.
import unsloth
from datasets import load_dataset

from speftr import PESFT, PESFTConfig


if TYPE_CHECKING:
    from collections.abc import Callable, Mapping

    from datasets import Dataset
    from transformers import PreTrainedTokenizerBase


DATASET_NAME = "TeeZee/dolly-15k-pirate-speech"
DEFAULT_MODEL = "unsloth/Qwen3-0.6B-unsloth-bnb-4bit"
DEFAULT_OUTPUT_DIR = "./models/speftr-instruction"
DEFAULT_SYSTEM_PROMPT: Final[str] = (
    "You are a pirate, always respond in pirate speech."
)


@runtime_checkable
class SupportsGenerationConfig(Protocol):
    """Protocol for models exposing a generation_config attribute.

    Attributes:
        generation_config: The model's generation configuration object.
    """

    generation_config: object


@runtime_checkable
class SupportsThinkingToggle(Protocol):
    """Protocol for configs exposing an enable_thinking flag.

    Attributes:
        enable_thinking: Whether the chat template emits thinking tokens.
    """

    enable_thinking: bool


@runtime_checkable
class SupportsDefaultSystemPrompt(Protocol):
    """Protocol for tokenizers with a default_system_prompt attribute.

    Attributes:
        default_system_prompt: System prompt used when a conversation has
            none.
    """

    default_system_prompt: str


def _normalize_system_prompt(raw_prompt: str) -> str:
    """Normalize system prompt input and fall back to the default.

    Args:
        raw_prompt: User-supplied system prompt.

    Returns:
        The stripped prompt, or ``DEFAULT_SYSTEM_PROMPT`` if it is blank.
    """
    prompt = raw_prompt.strip()
    if not prompt:
        return DEFAULT_SYSTEM_PROMPT
    return prompt


def _disable_thinking_mode(model: object) -> None:
    """Disable thinking mode when the model supports it.

    Models without a ``generation_config``, or whose config lacks an
    ``enable_thinking`` flag, are left untouched.

    Args:
        model: Loaded model whose generation config is updated in place.

    Returns:
        None. The model's generation config is mutated in place.
    """
    if not isinstance(model, SupportsGenerationConfig):
        return
    generation_config = model.generation_config
    if isinstance(generation_config, SupportsThinkingToggle):
        generation_config.enable_thinking = False


def _set_default_system_prompt(tokenizer: object, system_prompt: str) -> None:
    """Assign the default system prompt when supported by the tokenizer.

    Args:
        tokenizer: Tokenizer updated in place if it has a
            ``default_system_prompt`` attribute.
        system_prompt: Prompt to assign.

    Returns:
        None. The tokenizer is mutated in place.
    """
    if isinstance(tokenizer, SupportsDefaultSystemPrompt):
        tokenizer.default_system_prompt = system_prompt


def _normalize_column(value: object) -> list[str]:
    """Normalize a dataset column into a list of strings.

    ``PESFT.train`` passes batched columns (lists); Unsloth also probes the
    formatting function once with a single unbatched row (scalars).

    Args:
        value: A batched column (list), a single value, or ``None``.

    Returns:
        One string per item, with ``None`` items as ``""``; an empty list
        for ``None``; a one-element list for a scalar.
    """
    if isinstance(value, list):
        return [str(item) if item is not None else "" for item in value]
    if value is None:
        return []
    return [str(value)]


def _user_content(instruction: str, context: str) -> str:
    """Build the user turn of one Dolly row.

    Args:
        instruction: Stripped instruction, possibly empty.
        context: Stripped context passage, possibly empty.

    Returns:
        The instruction, followed by ``Context:`` and the context when both
        exist; whichever one exists otherwise; a placeholder when both are
        empty.
    """
    if instruction and context:
        return f"{instruction}\n\nContext:\n{context}"
    return instruction or context or "Ahoy matey, respond to this prompt."


def _value_at(values: list[str], index: int) -> str:
    """Return ``values[index]`` stripped, or ``""`` past the end.

    Args:
        values: A normalized column.
        index: Row index.

    Returns:
        The stripped value, or ``""`` when the column is shorter.
    """
    return values[index].strip() if index < len(values) else ""


def _build_conversations_from_columns(
    batch: Mapping[str, object],
) -> list[list[dict[str, str]]]:
    """Construct conversations from instruction/context/response columns.

    The user turn comes from ``_user_content``. The assistant turn is added
    only for a non-empty response. Missing columns are treated as empty,
    and an empty batch yields one placeholder conversation.

    Args:
        batch: Batched Dolly rows keyed by column name.

    Returns:
        One conversation (list of role/content messages) per row.
    """
    instructions = _normalize_column(batch.get("instruction"))
    contexts = _normalize_column(batch.get("context"))
    responses = _normalize_column(batch.get("response"))
    num_examples = max(len(instructions), len(contexts), len(responses), 1)

    conversations: list[list[dict[str, str]]] = []
    for index in range(num_examples):
        user_content = _user_content(
            _value_at(instructions, index), _value_at(contexts, index)
        )
        conversation = [{"role": "user", "content": user_content}]
        response = _value_at(responses, index)
        if response:
            conversation.append({"role": "assistant", "content": response})
        conversations.append(conversation)

    return conversations


def _extract_conversations(
    batch: Mapping[str, object],
) -> list[list[dict[str, str]]]:
    """Derive conversations from a batch, preferring prebuilt chat messages.

    Args:
        batch: Batched rows; a non-empty ``messages`` column is used as is,
            otherwise conversations are built from the Dolly columns.

    Returns:
        One conversation (list of role/content messages) per row; a single
        conversation when ``messages`` holds one unbatched conversation.
    """
    raw_messages = batch.get("messages", [])

    if isinstance(raw_messages, dict) or (
        isinstance(raw_messages, list)
        and raw_messages
        and isinstance(raw_messages[0], dict)
    ):
        single = cast("list[dict[str, str]]", raw_messages)
        return [single]

    if isinstance(raw_messages, list) and raw_messages:
        return cast("list[list[dict[str, str]]]", raw_messages)

    return _build_conversations_from_columns(batch)


def _inject_system_prompt(
    messages: list[dict[str, str]],
    system_prompt: str,
) -> list[dict[str, str]]:
    """Insert or replace the leading system prompt in a conversation.

    Args:
        messages: Conversation, left unmodified.
        system_prompt: Content of the system message.

    Returns:
        A new conversation starting with exactly one system message.
    """
    if messages and messages[0].get("role") == "system":
        return [
            {"role": "system", "content": system_prompt},
            *messages[1:],
        ]
    return [
        {"role": "system", "content": system_prompt},
        *messages,
    ]


def _format_conversations(
    conversations: list[list[dict[str, str]]],
    tokenizer: PreTrainedTokenizerBase,
    system_prompt: str,
) -> list[str]:
    """Apply the chat template to prepared conversations.

    Args:
        conversations: Conversations to render.
        tokenizer: Tokenizer providing the chat template and BOS token.
        system_prompt: System prompt injected into every conversation.

    Returns:
        One rendered training text per conversation, unchanged: Unsloth
        detects the template's BOS and does not add a second one.

    Raises:
        TypeError: If the chat template does not render to a string.
    """
    texts: list[str] = []
    for messages in conversations:
        formatted_messages = _inject_system_prompt(messages, system_prompt)
        formatted_output = tokenizer.apply_chat_template(
            formatted_messages,
            tokenize=False,
            add_generation_prompt=False,
        )
        if not isinstance(formatted_output, str):
            msg = "Chat template must produce string output."
            raise TypeError(msg)
        texts.append(formatted_output)
    return texts


def _build_format_batch(
    tokenizer: PreTrainedTokenizerBase,
    system_prompt: str,
) -> Callable[[Mapping[str, object]], list[str]]:
    """Create a formatting function bound to tokenizer and system prompt.

    Args:
        tokenizer: Tokenizer providing the chat template.
        system_prompt: System prompt injected into every conversation.

    Returns:
        Function mapping a dataset batch to rendered training texts.
    """

    def format_batch(batch: Mapping[str, object]) -> list[str]:
        """Render a dataset batch into training texts.

        Args:
            batch: Batched rows keyed by column name.

        Returns:
            One rendered training text per conversation in the batch.
        """
        conversations = _extract_conversations(batch)
        return _format_conversations(conversations, tokenizer, system_prompt)

    return format_batch


def parse_args() -> argparse.Namespace:
    """Parse the command-line options this example exposes.

    Returns:
        Namespace with model, template, LoRA, optimisation, data split and
        output settings.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Fine-tune an instruction-following model with PESFT on the "
            "TeeZee/dolly-15k-pirate-speech dataset."
        )
    )

    parser.add_argument(
        "--model_name_or_path",
        type=str,
        default=DEFAULT_MODEL,
        help=(f"Base model to load. Defaults to {DEFAULT_MODEL}."),
    )
    parser.add_argument(
        "--max_seq_length",
        type=int,
        default=2048,
        help="Maximum sequence length in tokens (default: 2048).",
    )
    parser.add_argument(
        "--load_in_4bit",
        action="store_true",
        help="Enable 4-bit loading (default: disabled).",
    )
    parser.add_argument(
        "--chat_template",
        type=str,
        default="chatml",
        help="Chat template to apply (default: chatml).",
    )
    parser.add_argument(
        "--system_prompt",
        type=str,
        default=DEFAULT_SYSTEM_PROMPT,
        help=(
            "System prompt inserted as the first conversation turn "
            "(default: pirate instructions)."
        ),
    )
    parser.add_argument(
        "--lora_r",
        type=int,
        default=8,
        help="LoRA rank (default: 8).",
    )
    parser.add_argument(
        "--lora_alpha",
        type=int,
        default=32,
        help="LoRA alpha (default: 32).",
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=2e-4,
        help="Learning rate (default: 2e-4).",
    )
    parser.add_argument(
        "--weight_decay",
        type=float,
        default=0.0,
        help="Weight decay (default: 0.0).",
    )
    parser.add_argument(
        "--scheduler",
        type=str,
        choices=["constant", "constant_with_warmup", "linear", "cosine"],
        default="constant",
        help=(
            "Learning rate scheduler: 'constant', 'constant_with_warmup', "
            "'linear', or 'cosine' (default: constant)."
        ),
    )
    parser.add_argument(
        "--warmup_ratio",
        type=float,
        default=0.0,
        help="Portion of training steps used for warmup (default: 0.0).",
    )
    parser.add_argument(
        "--per_device_batch_size",
        type=int,
        default=8,
        help="Per-device train batch size (default: 8).",
    )
    parser.add_argument(
        "--per_device_eval_batch_size",
        type=int,
        default=8,
        help="Per-device eval batch size (default: 8).",
    )
    parser.add_argument(
        "--gradient_accumulation_steps",
        type=int,
        default=2,
        help="Gradient accumulation steps (default: 2).",
    )
    parser.add_argument(
        "--max_grad_norm",
        type=float,
        default=0.3,
        help="Gradient clipping norm (default: 0.3).",
    )
    parser.add_argument(
        "--num_epochs",
        type=int,
        default=2,
        help="Number of training epochs (default: 2).",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help=(
            "Directory for checkpoints and artifacts (default: "
            f"{DEFAULT_OUTPUT_DIR})."
        ),
    )
    parser.add_argument(
        "--save_method",
        type=str,
        default="lora",
        help=(
            "'lora' saves the adapters; 'merged_16bit' saves a full model "
            "with the adapters merged in (default: lora)."
        ),
    )
    parser.add_argument(
        "--packing",
        action="store_true",
        help="Enable sequence packing (default: disabled).",
    )
    parser.add_argument(
        "--eval_ratio",
        type=float,
        default=0.05,
        help="Fraction of examples reserved for evaluation (default: 0.05).",
    )
    parser.add_argument(
        "--random_state",
        type=int,
        default=0,
        help=(
            "Random seed for the train/eval split and LoRA initialisation "
            "(default: 0)."
        ),
    )

    return parser.parse_args()


def _build_config(args: argparse.Namespace) -> PESFTConfig:
    """Map the CLI options onto a ``PESFTConfig`` for chat SFT.

    Fields not set here keep the ``PESFTConfig`` defaults (LoRA on all
    attention and MLP projections, per-epoch eval and save, best
    checkpoint by ``eval_loss`` reloaded at the end).

    Args:
        args: Options from ``parse_args``.

    Returns:
        The training configuration.
    """
    config = PESFTConfig()

    config.model_name_or_path = args.model_name_or_path
    config.max_seq_length = args.max_seq_length
    config.load_in_4bit = args.load_in_4bit

    # Loss only on assistant turns: tokens after response_part up to the
    # next instruction_part are trained. The markers are ChatML's, so they
    # match --chat_template chatml (and Qwen's own templates); another
    # template needs its own markers here.
    config.chat_template = args.chat_template
    config.train_on_responses = True
    config.instruction_part = "<|im_start|>user\n"
    config.response_part = "<|im_start|>assistant\n"

    config.lora_r = args.lora_r
    config.lora_alpha = args.lora_alpha

    config.learning_rate = args.learning_rate
    config.weight_decay = args.weight_decay
    config.scheduler = args.scheduler
    config.warmup_ratio = args.warmup_ratio
    config.per_device_train_batch_size = args.per_device_batch_size
    config.per_device_eval_batch_size = args.per_device_eval_batch_size
    config.gradient_accumulation_steps = args.gradient_accumulation_steps
    config.max_grad_norm = args.max_grad_norm
    config.num_train_epochs = args.num_epochs

    config.output_dir = args.output_dir
    config.save_method = args.save_method
    config.packing = args.packing
    config.random_state = args.random_state
    config.report_to = "none"

    return config


def _load_datasets(eval_ratio: float, seed: int) -> tuple[Dataset, Dataset]:
    """Load the Dolly pirate dataset and split off an evaluation set.

    Args:
        eval_ratio: Fraction of rows held out for evaluation, in (0, 1).
        seed: Seed for the random split.

    Returns:
        ``(train_dataset, eval_dataset)`` with the columns ``instruction``,
        ``context`` (often empty), ``response`` and ``category``.

    Raises:
        ValueError: If ``eval_ratio`` is not strictly between 0 and 1.
    """
    if not 0 < eval_ratio < 1:
        msg = "eval_ratio must be between 0 and 1 (exclusive)."
        raise ValueError(msg)

    dataset = cast("Dataset", load_dataset(DATASET_NAME, split="train"))
    split = dataset.train_test_split(test_size=eval_ratio, seed=seed)
    return split["train"], split["test"]


def main() -> None:
    """Instruction-tune the model and save it.

    Runs ``PESFT(config)`` then ``load_model()``, ``train()`` and
    ``save_model()``, printing one formatted training row first.

    Returns:
        None. The adapters (or merged model, per ``--save_method``),
        tokenizer, ``speftr.json``, ``training_args.json`` and per-epoch
        checkpoints are written to ``--output_dir``.
    """
    args = parse_args()
    print(unsloth.__version__)

    config = _build_config(args)
    trainer = PESFT(config)
    # The returned tokenizer already has the configured chat template.
    model, tokenizer = trainer.load_model()

    _disable_thinking_mode(model)
    system_prompt = _normalize_system_prompt(args.system_prompt)
    _set_default_system_prompt(tokenizer, system_prompt)

    format_batch = _build_format_batch(tokenizer, system_prompt)
    train_dataset, eval_dataset = _load_datasets(
        eval_ratio=args.eval_ratio,
        seed=config.random_state,
    )

    # Printing one rendered row is the quickest check that the template
    # and the instruction_part/response_part markers line up.
    preview_data = train_dataset[:1]
    preview_texts = format_batch(preview_data)
    if preview_texts:
        preview_header = "Preview: formatted conversation sent to the model"
        print(preview_header)
        print("-" * len(preview_header))
        print(preview_texts[0])
        print("-" * len(preview_header))

    trainer.train(train_dataset, eval_dataset, format_batch)
    trainer.save_model()


if __name__ == "__main__":
    main()
